### PR TITLE
Add full-rank Laplace approximation

### PR DESCRIPTION
**Pull request by eb8680**
@ae-foster this PR slightly modifies the internals of `LinearModelLaplaceGuide` and adds a full-rank Laplace approximation for EIG estimation in models with multiple random variables (as opposed to the block-diagonal approximation in #7, which is identical for one random variable).

Missing: 
- [ ] adding to tests/examples with multiple variables

~~Blocked by #8?~~

### CODE REVIEW

**Comment by ae-foster** [comment]
Thanks @eb8680 this looks great. I've merged #8 and fixed the resulting conflicts (though do double check things still run smoothly, the function `iter_iaranges_to_shape` moved file which could have broken something). One thing to mention that changed in #8 was https://github.com/ae-foster/pyro/pull/8#discussion_r253460784 which might effect your testing.

In terms of examples, we can try out the full Laplace on my normal inverse gamma example-- the diagonal worked very well but there could be a detectable difference switching to a full approximation.

Do you want me to merge now or wait for you to add tests/examples to this branch? Would be nice to have a test/example with multiple variables if you have time.

**Comment by eb8680** [comment]
I'll add a test case first

**Comment by ae-foster** [comment]
@eb8680 want to try and get this in before #22 ?

**Comment by eb8680** [comment]
> want to try and get this in before #22 ?

Nah, no need to block everything on this PR.  A better long-term solution to Laplace approximation for OED would be to reuse more of the Laplace approximation code in `pyro.contrib.autoguide`, which has already dealt with the plumbing issues holding up this PR related to full-rank Laplace approximation for multiple variables with different constrained supports.

**Pull request closed without merging**
